### PR TITLE
Address removal of .tar.gz (0.5.0) and bare versions (0.6.0)

### PR DESCRIPTION
**Pull request by auvik-bheesham**
Addresses #1

### CODE REVIEW

**Comment by the-cashman** [comment]
Great thank you! I apologize for the wait for some reason my github notifications are not working.

Could you please address the errors in CI? I'll get it merged ASAP once addressed.

**Comment by auvik-bheesham** [comment]
All cool! I submitted a follow-up commit to run `lib/utils.bash` through shfmt -- it now doesn't fail locally so I'm guessing it'll pass in the workflow.

**Comment by bheesham** [comment]
@devlincashman :wave: I think this might be ready for another run at CI.

**Comment by edubxb** [comment]
Hello. Is there any chance of having this PR merged?

Thanks!

**Comment by edubxb** [comment]
Bump!

**Pull request closed without merging**
